name: Publish Python Package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4
  
        - name: Install uv
          uses: astral-sh/setup-uv@v3
  
        - name: "Set up Python"
          uses: actions/setup-python@v5
          with:
            python-version-file: ".python-version"

        - name: "Build"
          run: uv build

        - name: Publish to PyPI
          run: uv publish
          env:
            UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}